-- ----------------------------------------------------------------
-- This is an attempt to create a full transactional MaNGOS update
-- Now compatible with newer MySql Databases (v1.5)
-- ----------------------------------------------------------------
DROP PROCEDURE IF EXISTS `update_mangos`;

DELIMITER $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `update_mangos`()
BEGIN
    DECLARE bRollback BOOL  DEFAULT FALSE ;
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET `bRollback` = TRUE;

    -- Current Values (TODO - must be a better way to do this)
    SET @cCurVersion := (SELECT `version` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
    SET @cCurStructure := (SELECT `structure` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
    SET @cCurContent := (SELECT `content` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);

    -- Expected Values
    SET @cOldVersion = '23';
    SET @cOldStructure = '01';
    SET @cOldContent = '001';

    -- New Values
    SET @cNewVersion = '23';
    SET @cNewStructure = '02';
    SET @cNewContent = '001';
                            -- DESCRIPTION IS 30 Characters MAX
    SET @cNewDescription = 'difficulty key spaces';
                        -- COMMENT is 150 Characters MAX
    SET @cNewComment = 'instance_reset.difficulty, characters.dungeon_difficulty and groups.difficulty now hold the internal 0-based Difficulty, not the raw client id';

    -- Evaluate all settings
    SET @cCurResult := (SELECT `description` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
    SET @cOldResult := (SELECT `description` FROM `db_version` WHERE `version`=@cOldVersion AND `structure`=@cOldStructure AND `content`=@cOldContent);
    SET @cNewResult := (SELECT `description` FROM `db_version` WHERE `version`=@cNewVersion AND `structure`=@cNewStructure AND `content`=@cNewContent);

    IF (@cCurResult = @cOldResult) THEN    -- Does the current version match the expected version
        -- APPLY UPDATE
        START TRANSACTION;
        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
        -- -- PLACE UPDATE SQL BELOW -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -

-- ============================================================================
-- `instance_reset`.`difficulty` changes key space
-- ============================================================================
-- The core separated the raw 5.4.8 client DifficultyID from its internal
-- 0-based Difficulty. `instance_reset` is written by the reset scheduler, and
-- every row already in the table was keyed on the RAW client id.
--
-- The two spaces do not agree on any id except 0, so the existing rows would be
-- silently reinterpreted:
--
--     raw 1 (5-man normal)  -> read as internal 1 = HEROIC
--     raw 2 (5-man heroic)  -> read as internal 2 = CHALLENGE
--     raw 3 (raid 10 normal)-> read as internal 3 = 25-player HEROIC
--
-- A stale 10-normal reset timestamp applied as 25-heroic is not a cosmetic
-- error, so the rows cannot be left in place and cannot be translated in situ
-- either: a legacy table can hold an ambiguous raw-3 row whose raw-4/5/6
-- companions have already been deleted, which passes every sniff test while
-- still being wrong.
--
-- The table is a SCHEDULE, not player data. Every row is regenerated by
-- MapPersistentStateManager::LoadResetTimes on the next start, from the
-- MapDifficulty DBC and the existing instance saves. Emptying it costs nothing
-- beyond recomputing reset times, and no character, group or instance binding
-- is touched.
--
-- DELETE rather than TRUNCATE deliberately: TRUNCATE is DDL and would commit
-- implicitly, breaking the transaction this update runs inside.
-- ============================================================================

DELETE FROM `instance_reset`;

-- ============================================================================
-- `characters`.`dungeon_difficulty` and `groups`.`difficulty` change key space
-- ============================================================================
-- The same key-space split reaches saved player state, by a different route.
--
-- The old dungeon finder wrote a RAW client DifficultyID straight into the
-- internal enum:
--
--     LFGMgr::CreateDungeonGroup
--         pGroup->SetDungeonDifficulty(Difficulty(dungeon->DifficultyID));
--
-- Group::SetDungeonDifficulty is not session-local. It writes `groups`.
-- `difficulty` directly and pushes the value into every member, which the
-- character save then persists to `characters`.`dungeon_difficulty`. One
-- completed LFG run therefore left the whole party's saved difficulty holding a
-- raw id.
--
-- Until now that was self-consistent and invisible AT THE PORTAL: the old lookup
-- was ALSO keyed on raw ids, so a stored raw 2 found the heroic MapDifficulty row
-- and the area trigger let the player through. It is worth being exact about what
-- happened next, because it sets the severity -- the map was then instantiated at
-- spawn mode 2, and no five-man map carries a single bit-2 creature or gameobject
-- spawn, so the dungeon they entered was empty. The old behaviour was not
-- working; it was broken in a quieter way.
--
-- The core has now moved the lookup to the internal key space, where 2 means
-- CHALLENGE. Ordinary heroic dungeons have no challenge row, so those characters
-- are now refused outright with AREA_LOCKSTATUS_MISSING_DIFFICULTY.
--
-- That state is not recoverable in game. The client's difficulty setter opcode
-- has no registered handler, so an affected player cannot select another
-- difficulty to escape it. Without this statement the only remedy is a manual
-- database edit.
--
-- CLAMPED TO 0, NOT TRANSLATED. Mapping raw->internal would look more faithful
-- and would be worse. The dungeon whose DifficultyID was read came from
-- LookupEntry on a store that was indexed by ROW ORDINAL rather than by id, so
-- the tier that got stored belonged to an unrelated dungeon and never described
-- what the player queued for. There is no intent in these values to preserve;
-- translating noise would only make it look deliberate. Normal is the safe
-- landing point because it is the tier every character already defaults to and
-- the one the overwhelming majority of instanceable maps offer.
--
-- Not ALL of them, which an earlier version of this comment claimed. Eight
-- maps have no normal tier: the three heroic-only five-mans -- End Time (938),
-- Well of Eternity (939) and Hour of Twilight (940), each shipping a single
-- raw-2 row -- and five scenario maps (1024, 1049, 1155, 1157, 1161) that ship
-- only raw 11/12 and end with no usable tier at all. Those eight are
-- unenterable at any stored value, before this update and after it, so
-- clamping neither causes nor cures their problem. The claim is corrected
-- rather than dropped because it was the stated justification for the clamp,
-- and the justification that actually holds is the narrower one above.
--
-- Safe because the structure gate makes the key space unambiguous. A database
-- still on structure 01 has only ever been written by cores predating the
-- split, and in those the sole origin of a non-zero dungeon difficulty was the
-- LFG cast above -- every other caller either propagates an existing value,
-- loads one, or belongs to an opcode handler that was never registered. So at
-- this point every non-zero value is raw by construction, and there are no
-- correctly-keyed values here to damage.
--
-- `groups`.`raiddifficulty` is deliberately NOT touched. It has no pre-split
-- writer at all: the LFG path called only the dungeon setter, and the raid
-- opcode handler was likewise unregistered, so the column can only hold its
-- default. Clamping it would be an unjustified write to player data.
--
-- Nor is a RAID tier recovered out of `groups`.`difficulty` before it is
-- cleared. The old LFG path did send raids through the dungeon setter, so a raw
-- raid id (3, 4, 5, 6, 9) could be sitting in that column -- but it is not worth
-- migrating into `raiddifficulty`, for two reasons. The core already refuses it:
-- Group::LoadGroupFromDB clamps anything above internal HEROIC to NORMAL, so
-- every one of those ids is discarded at load whether this update runs or not.
-- And it never meant what it appears to mean: it was read through a LookupEntry
-- that returned the Nth ROW rather than the row with that id, so the tier
-- belonged to an unrelated dungeon. Promoting it would turn noise into a raid
-- difficulty the group never chose.
--
-- WHAT THIS UPDATE DOES NOT FIX, stated because an admin should not have to
-- discover it: a pre-split LFG run that stored raw 1 also created its `instance`
-- row at difficulty 1, and internal 1 is a legitimate HEROIC save. Clearing the
-- owner's selected tier does not remove it, so a character can keep a heroic
-- lockout for a dungeon they queued for on normal, until it resets.
--
-- It is left alone because it cannot be identified. A stale raw 1 is numerically
-- identical to a heroic save a player genuinely earned, and it carries the same
-- reset shape, so no test separates them. Deleting every difficulty-1 instance
-- row would destroy real lockouts to clear imaginary ones, which is a far worse
-- trade than one stale lockout expiring on its own.
-- ============================================================================

UPDATE `characters` SET `dungeon_difficulty` = 0 WHERE `dungeon_difficulty` <> 0;
UPDATE `groups` SET `difficulty` = 0 WHERE `difficulty` <> 0;

        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
        -- -- PLACE UPDATE SQL ABOVE -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -

        -- If we get here ok, commit the changes
        IF bRollback = TRUE THEN
            ROLLBACK;
            SHOW ERRORS;
            SELECT '* UPDATE FAILED *' AS `===== Status =====`,@cCurResult AS `===== DB is on Version: =====`;
        ELSE
            COMMIT;
            -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
            -- UPDATE THE DB VERSION
            -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
            INSERT INTO `db_version` VALUES (@cNewVersion, @cNewStructure, @cNewContent, @cNewDescription, @cNewComment);
            SET @cNewResult := (SELECT `description` FROM `db_version` WHERE `version`=@cNewVersion AND `structure`=@cNewStructure AND `content`=@cNewContent);

            SELECT '* UPDATE COMPLETE *' AS `===== Status =====`,@cNewResult AS `===== DB is now on Version =====`;
        END IF;
    ELSE    -- Current version is not the expected version
        IF (@cCurResult = @cNewResult) THEN    -- Does the current version match the new version
            SELECT '* UPDATE SKIPPED *' AS `===== Status =====`,@cCurResult AS `===== DB is already on Version =====`;
        ELSE    -- Current version is not one related to this update
            IF(@cCurResult IS NULL) THEN    -- Something has gone wrong
                SELECT '* UPDATE FAILED *' AS `===== Status =====`,'Unable to locate DB Version Information' AS `============= Error Message =============`;
            ELSE
                IF(@cOldResult IS NULL) THEN    -- Something has gone wrong
                    SET @cCurVersion := (SELECT `version` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurStructure := (SELECT `STRUCTURE` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurContent := (SELECT `Content` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurOutput = CONCAT(@cCurVersion, '_', @cCurStructure, '_', @cCurContent, ' - ',@cCurResult);
                    SET @cOldResult = CONCAT('Rel',@cOldVersion, '_', @cOldStructure, '_', @cOldContent, ' - ','IS NOT APPLIED');
                    SELECT '* UPDATE SKIPPED *' AS `===== Status =====`,@cOldResult AS `=== Expected ===`,@cCurOutput AS `===== Found Version =====`;
                ELSE
                    SET @cCurVersion := (SELECT `version` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurStructure := (SELECT `STRUCTURE` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurContent := (SELECT `Content` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurOutput = CONCAT(@cCurVersion, '_', @cCurStructure, '_', @cCurContent, ' - ',@cCurResult);
                    SELECT '* UPDATE SKIPPED *' AS `===== Status =====`,@cOldResult AS `=== Expected ===`,@cCurOutput AS `===== Found Version =====`;
                END IF;
            END IF;
        END IF;
    END IF;
END $$

DELIMITER ;

-- Execute the procedure
CALL update_mangos();

-- Drop the procedure
DROP PROCEDURE IF EXISTS `update_mangos`;
