-- ----------------------------------------------------------------
-- This is an attempt to create a full transactional MaNGOS update
-- Now compatible with newer MySql Databases (v1.5)
-- ----------------------------------------------------------------
DROP PROCEDURE IF EXISTS `update_mangos`; 

DELIMITER $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `update_mangos`()
BEGIN
    DECLARE bRollback BOOL  DEFAULT FALSE ;
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET `bRollback` = TRUE;

    -- Current Values (TODO - must be a better way to do this)
    SET @cCurVersion := (SELECT `version` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
    SET @cCurStructure := (SELECT `structure` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
    SET @cCurContent := (SELECT `content` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);

    -- Expected Values
    SET @cOldVersion = '23'; 
    SET @cOldStructure = '02'; 
    SET @cOldContent = '077';

    -- New Values
    SET @cNewVersion = '23';
    SET @cNewStructure = '02';
    SET @cNewContent = '078';
                            -- DESCRIPTION IS 30 Characters MAX    
    SET @cNewDescription = 'Item_Template_Sanity';

                        -- COMMENT is 150 Characters MAX
    SET @cNewComment = 'Item_Template_Sanity';

    -- Evaluate all settings
    SET @cCurResult := (SELECT `description` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
    SET @cOldResult := (SELECT `description` FROM `db_version` WHERE `version`=@cOldVersion AND `structure`=@cOldStructure AND `content`=@cOldContent);
    SET @cNewResult := (SELECT `description` FROM `db_version` WHERE `version`=@cNewVersion AND `structure`=@cNewStructure AND `content`=@cNewContent);

    IF (@cCurResult = @cOldResult) THEN    -- Does the current version match the expected version
        -- APPLY UPDATE
        START TRANSACTION;
        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
        -- -- PLACE UPDATE SQL BELOW -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -

-- ============================================================
-- MaNGOS Four world DB update: item_template field sanity
-- Useless/invalid field values the core warns about every startup.
-- All statements are guarded (WHERE current value matches) and idempotent.
-- ============================================================

-- RequiredReputationRank set while RequiredReputationFaction=0 (rank is useless): 460 item(s)
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=79785 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=80894 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=81062 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84353 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84354 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84355 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84382 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84387 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84390 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84395 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84402 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84403 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84423 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84424 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84434 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84435 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84456 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84457 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84467 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84482 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84550 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84873 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84880 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84882 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84946 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84947 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84948 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84949 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84950 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84951 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84952 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84953 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84954 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84955 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84956 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84957 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84958 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84959 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=84960 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=85049 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=85051 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=85060 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=85092 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=85093 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=85094 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=85095 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=85096 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=85097 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=85098 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=85099 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=85100 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=85101 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=85102 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=85103 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=85104 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=85105 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=85106 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=85267 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=85268 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=85269 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=85973 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=87465 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=87649 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=87652 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=88178 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=88203 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=88258 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=90176 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91109 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91110 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91111 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91112 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91113 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91114 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91167 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91168 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91176 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91177 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91184 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91185 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91193 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91194 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91212 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91213 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91214 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91215 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91242 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91243 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91261 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91262 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91277 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91278 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91279 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91280 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91297 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91298 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91299 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91300 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91335 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91336 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91350 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91351 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91378 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91379 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91462 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91464 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91466 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91520 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91529 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91537 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91546 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91565 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91567 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91595 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91614 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91630 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91632 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91650 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91652 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91688 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91703 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91731 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=91901 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93243 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93244 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93245 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93246 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93247 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93248 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93249 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93250 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93251 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93252 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93253 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93254 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93255 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93256 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93257 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93258 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93259 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93260 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93261 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93262 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93263 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93264 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93265 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93266 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93267 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93268 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93269 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93270 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93271 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93272 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93273 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93274 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93275 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93276 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93277 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93278 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93279 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93280 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93323 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93324 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93325 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93326 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93327 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93328 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93329 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93330 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93331 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93332 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93333 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93334 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93335 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93336 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93337 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93338 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93339 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93340 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93344 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93349 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93428 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93429 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93430 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93463 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93468 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93472 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93477 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93488 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93489 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93504 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93521 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93522 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93532 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93533 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93543 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93544 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93566 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93574 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=93589 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=94295 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=94330 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=94353 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=94358 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=94360 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=94376 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=94382 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=94393 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=94400 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=94410 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=94424 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=94425 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=94440 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=94464 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=94477 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=94478 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=94480 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=94483 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=94491 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=95057 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97187 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97188 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97189 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97190 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97191 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97192 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97193 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97194 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97195 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97196 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97203 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97204 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97205 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97206 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97207 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97208 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97209 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97210 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97211 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97212 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97523 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97840 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=97930 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=98165 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=98763 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=98764 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=98765 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=98794 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=98799 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=98802 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=98807 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=98814 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=98815 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=98830 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=98840 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=98848 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=98849 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=98859 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=98860 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=98881 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=98889 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=98904 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=99781 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=99782 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=99783 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=99816 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=99821 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=99825 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=99830 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=99841 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=99842 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=99857 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=99867 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=99875 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=99876 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=99886 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=99887 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=99903 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=99911 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=99926 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=99991 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100023 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100028 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100030 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100046 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100052 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100063 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100070 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100080 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100094 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100095 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100110 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100134 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100147 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100148 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100150 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100153 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100161 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100205 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100206 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100207 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100208 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100209 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100210 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100263 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100264 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100272 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100273 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100280 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100281 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100289 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100290 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100308 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100309 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100310 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100311 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100338 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100339 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100357 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100358 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100373 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100374 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100375 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100376 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100393 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100394 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100395 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100396 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100425 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100426 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100440 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100441 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100468 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100469 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100560 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100583 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100588 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100590 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100606 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100612 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100623 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100630 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100640 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100654 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100655 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100670 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100694 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100707 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100708 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100710 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100713 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=100721 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102139 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102141 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102143 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102534 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102617 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102640 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102645 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102647 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102662 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102668 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102677 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102684 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102694 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102708 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102709 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102724 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102748 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102761 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102762 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102764 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102767 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102775 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102814 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102837 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102842 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102844 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102859 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102865 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102874 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102881 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102891 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102905 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102906 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102921 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102945 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102958 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102959 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102961 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102964 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102972 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102991 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102992 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=102993 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103014 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103018 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103022 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103026 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103033 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103034 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103047 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103056 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103064 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103065 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103073 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103074 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103088 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103095 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103108 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103134 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103136 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103138 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103154 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103155 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103156 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103189 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103194 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103198 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103203 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103213 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103214 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103229 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103239 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103247 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103248 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103258 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103259 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103275 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103283 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103298 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103351 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103352 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103353 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103386 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103391 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103395 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103400 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103410 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103411 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103426 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103436 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103444 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103445 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103455 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103456 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103472 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103480 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103495 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103983 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103984 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=103985 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=104045 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=104197 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=104269 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=104279 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=104280 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=104281 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=104282 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;
UPDATE `item_template` SET `RequiredReputationRank`=0 WHERE `entry`=105920 AND `RequiredReputationFaction`=0 AND `RequiredReputationRank`>0;

-- DisenchantID on non-disenchantable item classes (core ignores it): 234 item(s)
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=18984 AND `DisenchantID`=9;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=18986 AND `DisenchantID`=9;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=22345 AND `DisenchantID`=39;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=22395 AND `DisenchantID`=39;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=22396 AND `DisenchantID`=48;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=22397 AND `DisenchantID`=39;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=22398 AND `DisenchantID`=39;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=22399 AND `DisenchantID`=48;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=22400 AND `DisenchantID`=39;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=22401 AND `DisenchantID`=39;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=22402 AND `DisenchantID`=48;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=23004 AND `DisenchantID`=48;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=23005 AND `DisenchantID`=48;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=23006 AND `DisenchantID`=48;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=23197 AND `DisenchantID`=39;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=23198 AND `DisenchantID`=39;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=23199 AND `DisenchantID`=39;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=23200 AND `DisenchantID`=39;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=23201 AND `DisenchantID`=39;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=23203 AND `DisenchantID`=39;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=24386 AND `DisenchantID`=40;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=24413 AND `DisenchantID`=40;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=25643 AND `DisenchantID`=41;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=25644 AND `DisenchantID`=41;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=25645 AND `DisenchantID`=41;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=25940 AND `DisenchantID`=40;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=27484 AND `DisenchantID`=41;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=27518 AND `DisenchantID`=41;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=27544 AND `DisenchantID`=41;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=27744 AND `DisenchantID`=41;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=27815 AND `DisenchantID`=41;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=27886 AND `DisenchantID`=41;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=27917 AND `DisenchantID`=41;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=28064 AND `DisenchantID`=13;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=28065 AND `DisenchantID`=13;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=28066 AND `DisenchantID`=13;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=28248 AND `DisenchantID`=41;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=28296 AND `DisenchantID`=41;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=28372 AND `DisenchantID`=41;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=28523 AND `DisenchantID`=52;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=28568 AND `DisenchantID`=52;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=28592 AND `DisenchantID`=52;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=29388 AND `DisenchantID`=52;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=29389 AND `DisenchantID`=52;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=29390 AND `DisenchantID`=52;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=30023 AND `DisenchantID`=52;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=30051 AND `DisenchantID`=52;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=30063 AND `DisenchantID`=52;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=30542 AND `DisenchantID`=11;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=30544 AND `DisenchantID`=11;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=31025 AND `DisenchantID`=41;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=31031 AND `DisenchantID`=41;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=31033 AND `DisenchantID`=41;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=32257 AND `DisenchantID`=52;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=32330 AND `DisenchantID`=52;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=32368 AND `DisenchantID`=52;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=32387 AND `DisenchantID`=41;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=33502 AND `DisenchantID`=52;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=33503 AND `DisenchantID`=52;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=33504 AND `DisenchantID`=52;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=33505 AND `DisenchantID`=52;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=33506 AND `DisenchantID`=52;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=33507 AND `DisenchantID`=52;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=33508 AND `DisenchantID`=52;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=33509 AND `DisenchantID`=52;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=33510 AND `DisenchantID`=52;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=35039 AND `DisenchantID`=35039;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=35040 AND `DisenchantID`=35040;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=35106 AND `DisenchantID`=35106;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=37573 AND `DisenchantID`=15;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=37574 AND `DisenchantID`=15;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=37575 AND `DisenchantID`=15;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=38295 AND `DisenchantID`=15;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=38360 AND `DisenchantID`=42;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=38361 AND `DisenchantID`=42;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=38362 AND `DisenchantID`=42;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=38363 AND `DisenchantID`=42;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=38364 AND `DisenchantID`=42;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=38365 AND `DisenchantID`=42;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=38366 AND `DisenchantID`=42;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=38367 AND `DisenchantID`=42;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=38368 AND `DisenchantID`=42;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=39715 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=39728 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=39757 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40191 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40207 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40267 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40268 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40321 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40322 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40337 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40342 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40705 AND `DisenchantID`=53;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40706 AND `DisenchantID`=53;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40707 AND `DisenchantID`=53;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40708 AND `DisenchantID`=53;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40709 AND `DisenchantID`=53;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40710 AND `DisenchantID`=53;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40711 AND `DisenchantID`=53;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40712 AND `DisenchantID`=53;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40713 AND `DisenchantID`=53;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40714 AND `DisenchantID`=53;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40715 AND `DisenchantID`=53;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40727 AND `DisenchantID`=40727;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40822 AND `DisenchantID`=42;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40867 AND `DisenchantID`=42;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40875 AND `DisenchantID`=42;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=40895 AND `DisenchantID`=40;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=45114 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=45144 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=45145 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=45169 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=45254 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=45255 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=45270 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=45436 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=45509 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=45510 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=46138 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=47661 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=47662 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=47664 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=47665 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=47666 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=47667 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=47668 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=47670 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=47671 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=47672 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=47673 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=48933 AND `DisenchantID`=40;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=50454 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=50455 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=50456 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=50457 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=50458 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=50459 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=50460 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=50461 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=50462 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=50463 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=50464 AND `DisenchantID`=54;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=51417 AND `DisenchantID`=51417;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=51423 AND `DisenchantID`=51423;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=51429 AND `DisenchantID`=51429;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=51437 AND `DisenchantID`=51437;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=51472 AND `DisenchantID`=51472;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=51478 AND `DisenchantID`=51478;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=51501 AND `DisenchantID`=51501;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=51507 AND `DisenchantID`=51507;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=51513 AND `DisenchantID`=51513;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=55248 AND `DisenchantID`=55248;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=55783 AND `DisenchantID`=55783;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=55800 AND `DisenchantID`=55800;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=55821 AND `DisenchantID`=55821;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=55852 AND `DisenchantID`=55852;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=56279 AND `DisenchantID`=56279;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=56316 AND `DisenchantID`=56316;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=56337 AND `DisenchantID`=56337;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=56350 AND `DisenchantID`=56350;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=56372 AND `DisenchantID`=56372;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=57297 AND `DisenchantID`=57297;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=59626 AND `DisenchantID`=59626;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=59637 AND `DisenchantID`=59637;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=59640 AND `DisenchantID`=59640;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=60223 AND `DisenchantID`=60223;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=61388 AND `DisenchantID`=61388;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=61389 AND `DisenchantID`=61389;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=61390 AND `DisenchantID`=61390;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=61391 AND `DisenchantID`=61391;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=61399 AND `DisenchantID`=61399;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=61437 AND `DisenchantID`=61437;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=61440 AND `DisenchantID`=61440;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=62240 AND `DisenchantID`=62240;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=62241 AND `DisenchantID`=62241;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=62242 AND `DisenchantID`=62242;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=62243 AND `DisenchantID`=62243;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=62244 AND `DisenchantID`=62244;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=62245 AND `DisenchantID`=62245;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=63460 AND `DisenchantID`=63460;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=63480 AND `DisenchantID`=63480;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=63487 AND `DisenchantID`=63487;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=63769 AND `DisenchantID`=63769;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=63772 AND `DisenchantID`=63772;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=63776 AND `DisenchantID`=63776;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=63888 AND `DisenchantID`=63888;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=63891 AND `DisenchantID`=63891;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=64671 AND `DisenchantID`=64671;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=64672 AND `DisenchantID`=64672;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=64673 AND `DisenchantID`=64673;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=64674 AND `DisenchantID`=64674;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=64676 AND `DisenchantID`=64676;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=64819 AND `DisenchantID`=64819;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=64820 AND `DisenchantID`=64820;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=64821 AND `DisenchantID`=64821;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=64822 AND `DisenchantID`=64822;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=65812 AND `DisenchantID`=65812;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=66048 AND `DisenchantID`=66048;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=66049 AND `DisenchantID`=66049;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=66050 AND `DisenchantID`=66050;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=66051 AND `DisenchantID`=66051;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=66912 AND `DisenchantID`=66912;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=66961 AND `DisenchantID`=66961;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=66988 AND `DisenchantID`=66988;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=67059 AND `DisenchantID`=67059;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=67110 AND `DisenchantID`=67110;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=68609 AND `DisenchantID`=68609;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=68612 AND `DisenchantID`=68612;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=70077 AND `DisenchantID`=70077;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=70078 AND `DisenchantID`=70078;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=70079 AND `DisenchantID`=70079;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=70405 AND `DisenchantID`=70405;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=70406 AND `DisenchantID`=70406;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=70407 AND `DisenchantID`=70407;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=70408 AND `DisenchantID`=70408;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=70629 AND `DisenchantID`=70629;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=70630 AND `DisenchantID`=70630;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=70939 AND `DisenchantID`=70939;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=71146 AND `DisenchantID`=71146;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=71147 AND `DisenchantID`=71147;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=71148 AND `DisenchantID`=71148;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=71149 AND `DisenchantID`=71149;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=72310 AND `DisenchantID`=72310;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=72328 AND `DisenchantID`=72328;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=72358 AND `DisenchantID`=72358;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=72456 AND `DisenchantID`=72456;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=75066 AND `DisenchantID`=75066;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=75069 AND `DisenchantID`=75069;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=75079 AND `DisenchantID`=75079;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=77080 AND `DisenchantID`=77080;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=77081 AND `DisenchantID`=77081;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=77082 AND `DisenchantID`=77082;
UPDATE `item_template` SET `DisenchantID`=0 WHERE `entry`=77083 AND `DisenchantID`=77083;

        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
        -- -- PLACE UPDATE SQL ABOVE -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -

        -- If we get here ok, commit the changes
        IF bRollback = TRUE THEN
            ROLLBACK;
            SHOW ERRORS;
            SELECT '* UPDATE FAILED *' AS `===== Status =====`,@cCurResult AS `===== DB is on Version: =====`;
        ELSE
            COMMIT;
            -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
            -- UPDATE THE DB VERSION
            -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
            INSERT INTO `db_version` VALUES (@cNewVersion, @cNewStructure, @cNewContent, @cNewDescription, @cNewComment);
            SET @cNewResult := (SELECT `description` FROM `db_version` WHERE `version`=@cNewVersion AND `structure`=@cNewStructure AND `content`=@cNewContent);

            SELECT '* UPDATE COMPLETE *' AS `===== Status =====`,@cNewResult AS `===== DB is now on Version =====`;
        END IF;
    ELSE    -- Current version is not the expected version
        IF (@cCurResult = @cNewResult) THEN    -- Does the current version match the new version
            SELECT '* UPDATE SKIPPED *' AS `===== Status =====`,@cCurResult AS `===== DB is already on Version =====`;
        ELSE    -- Current version is not one related to this update
            IF(@cCurResult IS NULL) THEN    -- Something has gone wrong
                SELECT '* UPDATE FAILED *' AS `===== Status =====`,'Unable to locate DB Version Information' AS `============= Error Message =============`;
            ELSE
                IF(@cOldResult IS NULL) THEN    -- Something has gone wrong
                    SET @cCurVersion := (SELECT `version` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurStructure := (SELECT `STRUCTURE` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurContent := (SELECT `Content` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurOutput = CONCAT(@cCurVersion, '_', @cCurStructure, '_', @cCurContent, ' - ',@cCurResult);
                    SET @cOldResult = CONCAT('Rel',@cOldVersion, '_', @cOldStructure, '_', @cOldContent, ' - ','IS NOT APPLIED');
                    SELECT '* UPDATE SKIPPED *' AS `===== Status =====`,@cOldResult AS `=== Expected ===`,@cCurOutput AS `===== Found Version =====`;
                ELSE
                    SET @cCurVersion := (SELECT `version` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurStructure := (SELECT `STRUCTURE` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurContent := (SELECT `Content` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurOutput = CONCAT(@cCurVersion, '_', @cCurStructure, '_', @cCurContent, ' - ',@cCurResult);
                    SELECT '* UPDATE SKIPPED *' AS `===== Status =====`,@cOldResult AS `=== Expected ===`,@cCurOutput AS `===== Found Version =====`;
                END IF;
            END IF;
        END IF;
    END IF;
END $$

DELIMITER ;

-- Execute the procedure
CALL update_mangos();

-- Drop the procedure
DROP PROCEDURE IF EXISTS `update_mangos`;


