-- ----------------------------------------------------------------
-- This is an attempt to create a full transactional MaNGOS update
-- Now compatible with newer MySql Databases (v1.5)
-- ----------------------------------------------------------------
DROP PROCEDURE IF EXISTS `update_mangos`; 

DELIMITER $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `update_mangos`()
BEGIN
    DECLARE bRollback BOOL  DEFAULT FALSE ;
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET `bRollback` = TRUE;

    -- Current Values (TODO - must be a better way to do this)
    SET @cCurVersion := (SELECT `version` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
    SET @cCurStructure := (SELECT `structure` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
    SET @cCurContent := (SELECT `content` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);

    -- Expected Values
    SET @cOldVersion = '23'; 
    SET @cOldStructure = '02'; 
    SET @cOldContent = '078';

    -- New Values
    SET @cNewVersion = '23';
    SET @cNewStructure = '02';
    SET @cNewContent = '079';
                            -- DESCRIPTION IS 30 Characters MAX    
    SET @cNewDescription = 'Quest_Template_Fixes';

                        -- COMMENT is 150 Characters MAX
    SET @cNewComment = 'Quest_Template_Fixes';

    -- Evaluate all settings
    SET @cCurResult := (SELECT `description` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
    SET @cOldResult := (SELECT `description` FROM `db_version` WHERE `version`=@cOldVersion AND `structure`=@cOldStructure AND `content`=@cOldContent);
    SET @cNewResult := (SELECT `description` FROM `db_version` WHERE `version`=@cNewVersion AND `structure`=@cNewStructure AND `content`=@cNewContent);

    IF (@cCurResult = @cOldResult) THEN    -- Does the current version match the expected version
        -- APPLY UPDATE
        START TRANSACTION;
        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
        -- -- PLACE UPDATE SQL BELOW -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -

-- ============================================================
-- MaNGOS Four world DB update: quest_template fixes
-- SrcItemCount, ReqSourceCount, removed reward spells and event/exploration SpecialFlags.
-- All statements are guarded (WHERE current value matches) and idempotent.
-- ============================================================

-- SrcItemId set but SrcItemCount=0 (core forces 1 at runtime): 275 quest(s)
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29422 AND `SrcItemId`=72583 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29523 AND `SrcItemId`=72109 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29585 AND `SrcItemId`=72578 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29637 AND `SrcItemId`=73369 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29664 AND `SrcItemId`=75008 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29678 AND `SrcItemId`=73791 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29693 AND `SrcItemId`=73265 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29714 AND `SrcItemId`=73800 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29718 AND `SrcItemId`=73802 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29728 AND `SrcItemId`=73837 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29732 AND `SrcItemId`=73861 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29752 AND `SrcItemId`=74771 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29753 AND `SrcItemId`=74808 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29757 AND `SrcItemId`=76727 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29758 AND `SrcItemId`=83767 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29767 AND `SrcItemId`=74614 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29782 AND `SrcItemId`=76174 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29809 AND `SrcItemId`=62768 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29812 AND `SrcItemId`=74612 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29821 AND `SrcItemId`=84157 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29837 AND `SrcItemId`=74768 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29856 AND `SrcItemId`=74925 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29880 AND `SrcItemId`=75220 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29893 AND `SrcItemId`=76128 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29895 AND `SrcItemId`=79812 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29902 AND `SrcItemId`=81927 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29911 AND `SrcItemId`=76110 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29915 AND `SrcItemId`=76100 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29918 AND `SrcItemId`=75208 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29925 AND `SrcItemId`=76483 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29932 AND `SrcItemId`=74030 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29935 AND `SrcItemId`=85507 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29936 AND `SrcItemId`=76305 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29939 AND `SrcItemId`=76262 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29947 AND `SrcItemId`=76370 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29950 AND `SrcItemId`=76350 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29951 AND `SrcItemId`=76362 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29966 AND `SrcItemId`=76336 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29969 AND `SrcItemId`=65897 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=29970 AND `SrcItemId`=76349 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30015 AND `SrcItemId`=76761 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30050 AND `SrcItemId`=77281 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30066 AND `SrcItemId`=77475 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30084 AND `SrcItemId`=78928 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30089 AND `SrcItemId`=79021 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30090 AND `SrcItemId`=79057 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30117 AND `SrcItemId`=81393 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30136 AND `SrcItemId`=78947 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30151 AND `SrcItemId`=79043 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30157 AND `SrcItemId`=78947 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30164 AND `SrcItemId`=79163 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30204 AND `SrcItemId`=85261 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30231 AND `SrcItemId`=79344 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30235 AND `SrcItemId`=87807 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30254 AND `SrcItemId`=80302 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30255 AND `SrcItemId`=79104 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30275 AND `SrcItemId`=79237 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30282 AND `SrcItemId`=84781 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30301 AND `SrcItemId`=85581 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30312 AND `SrcItemId`=84242 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30320 AND `SrcItemId`=89297 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30330 AND `SrcItemId`=80127 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30331 AND `SrcItemId`=79895 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30337 AND `SrcItemId`=79885 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30341 AND `SrcItemId`=89366 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30357 AND `SrcItemId`=79163 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30460 AND `SrcItemId`=79819 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30485 AND `SrcItemId`=80071 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30498 AND `SrcItemId`=86068 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30499 AND `SrcItemId`=86067 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30504 AND `SrcItemId`=86467 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30582 AND `SrcItemId`=80241 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30601 AND `SrcItemId`=80308 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30613 AND `SrcItemId`=80403 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30614 AND `SrcItemId`=80312 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30623 AND `SrcItemId`=80337 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30634 AND `SrcItemId`=80484 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30658 AND `SrcItemId`=80403 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30678 AND `SrcItemId`=80599 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30690 AND `SrcItemId`=81741 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30694 AND `SrcItemId`=80828 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30744 AND `SrcItemId`=81054 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30746 AND `SrcItemId`=80944 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30747 AND `SrcItemId`=81183 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30773 AND `SrcItemId`=81193 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30778 AND `SrcItemId`=81356 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30783 AND `SrcItemId`=81417 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30784 AND `SrcItemId`=81430 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30788 AND `SrcItemId`=81319 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30789 AND `SrcItemId`=81319 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30795 AND `SrcItemId`=81712 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30796 AND `SrcItemId`=81712 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30797 AND `SrcItemId`=81712 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30798 AND `SrcItemId`=81712 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30799 AND `SrcItemId`=81712 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30800 AND `SrcItemId`=81712 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30801 AND `SrcItemId`=81712 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30802 AND `SrcItemId`=81712 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30821 AND `SrcItemId`=81183 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30825 AND `SrcItemId`=81054 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30888 AND `SrcItemId`=81925 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30892 AND `SrcItemId`=82787 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30899 AND `SrcItemId`=83023 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30923 AND `SrcItemId`=81891 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30930 AND `SrcItemId`=82468 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30935 AND `SrcItemId`=81712 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30953 AND `SrcItemId`=82381 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30959 AND `SrcItemId`=82346 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=30972 AND `SrcItemId`=83136 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31002 AND `SrcItemId`=82807 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31004 AND `SrcItemId`=83062 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31009 AND `SrcItemId`=83276 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31016 AND `SrcItemId`=82808 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31023 AND `SrcItemId`=82870 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31032 AND `SrcItemId`=83768 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31055 AND `SrcItemId`=83076 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31061 AND `SrcItemId`=83134 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31068 AND `SrcItemId`=84586 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31082 AND `SrcItemId`=84267 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31085 AND `SrcItemId`=84771 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31087 AND `SrcItemId`=86009 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31089 AND `SrcItemId`=84119 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31093 AND `SrcItemId`=83770 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31094 AND `SrcItemId`=83771 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31095 AND `SrcItemId`=83772 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31096 AND `SrcItemId`=83774 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31097 AND `SrcItemId`=83773 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31100 AND `SrcItemId`=83777 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31101 AND `SrcItemId`=83778 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31102 AND `SrcItemId`=83779 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31103 AND `SrcItemId`=83780 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31112 AND `SrcItemId`=84157 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31141 AND `SrcItemId`=85160 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31146 AND `SrcItemId`=85164 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31150 AND `SrcItemId`=85174 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31156 AND `SrcItemId`=85196 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31165 AND `SrcItemId`=85203 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31168 AND `SrcItemId`=85205 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31182 AND `SrcItemId`=85231 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31185 AND `SrcItemId`=85955 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31187 AND `SrcItemId`=85972 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31200 AND `SrcItemId`=86532 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31235 AND `SrcItemId`=82807 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31254 AND `SrcItemId`=85688 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31255 AND `SrcItemId`=85694 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31261 AND `SrcItemId`=85783 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31265 AND `SrcItemId`=85869 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31268 AND `SrcItemId`=85884 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31279 AND `SrcItemId`=86392 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31312 AND `SrcItemId`=86404 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31315 AND `SrcItemId`=86421 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31319 AND `SrcItemId`=86511 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31325 AND `SrcItemId`=86433 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31326 AND `SrcItemId`=86434 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31328 AND `SrcItemId`=86435 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31329 AND `SrcItemId`=86436 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31341 AND `SrcItemId`=86465 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31362 AND `SrcItemId`=80071 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31398 AND `SrcItemId`=86533 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31439 AND `SrcItemId`=87202 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31486 AND `SrcItemId`=86392 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31487 AND `SrcItemId`=87394 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31488 AND `SrcItemId`=87261 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31489 AND `SrcItemId`=87262 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31496 AND `SrcItemId`=87400 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31507 AND `SrcItemId`=87841 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31514 AND `SrcItemId`=87388 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31516 AND `SrcItemId`=87390 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31537 AND `SrcItemId`=87558 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31538 AND `SrcItemId`=87763 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31539 AND `SrcItemId`=87812 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31598 AND `SrcItemId`=87871 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31599 AND `SrcItemId`=87878 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31661 AND `SrcItemId`=88538 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31677 AND `SrcItemId`=88715 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31679 AND `SrcItemId`=86009 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31682 AND `SrcItemId`=84119 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31705 AND `SrcItemId`=89113 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31709 AND `SrcItemId`=88966 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31734 AND `SrcItemId`=89612 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31735 AND `SrcItemId`=89624 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31743 AND `SrcItemId`=89602 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31754 AND `SrcItemId`=89123 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31768 AND `SrcItemId`=89605 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31769 AND `SrcItemId`=89769 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31786 AND `SrcItemId`=89169 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31787 AND `SrcItemId`=89170 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31788 AND `SrcItemId`=89171 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31789 AND `SrcItemId`=89172 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31790 AND `SrcItemId`=89173 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31791 AND `SrcItemId`=89174 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31792 AND `SrcItemId`=89175 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31793 AND `SrcItemId`=89176 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31794 AND `SrcItemId`=85477 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31795 AND `SrcItemId`=85557 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31796 AND `SrcItemId`=85558 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31797 AND `SrcItemId`=89178 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31798 AND `SrcItemId`=89179 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31799 AND `SrcItemId`=89180 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31800 AND `SrcItemId`=89181 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31801 AND `SrcItemId`=89182 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31802 AND `SrcItemId`=89183 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31803 AND `SrcItemId`=89184 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31804 AND `SrcItemId`=89185 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31805 AND `SrcItemId`=89209 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31809 AND `SrcItemId`=89317 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31936 AND `SrcItemId`=89812 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31937 AND `SrcItemId`=89813 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31938 AND `SrcItemId`=89814 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=31948 AND `SrcItemId`=89902 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32105 AND `SrcItemId`=89209 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32154 AND `SrcItemId`=93187 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32181 AND `SrcItemId`=91834 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32182 AND `SrcItemId`=91835 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32183 AND `SrcItemId`=91836 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32184 AND `SrcItemId`=91834 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32185 AND `SrcItemId`=91835 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32186 AND `SrcItemId`=91836 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32209 AND `SrcItemId`=93761 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32214 AND `SrcItemId`=92475 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32218 AND `SrcItemId`=93751 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32226 AND `SrcItemId`=93803 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32231 AND `SrcItemId`=92060 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32235 AND `SrcItemId`=92019 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32236 AND `SrcItemId`=93026 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32238 AND `SrcItemId`=91902 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32268 AND `SrcItemId`=94905 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32284 AND `SrcItemId`=92501 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32295 AND `SrcItemId`=92441 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32305 AND `SrcItemId`=95352 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32319 AND `SrcItemId`=92510 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32359 AND `SrcItemId`=92563 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32368 AND `SrcItemId`=92756 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32371 AND `SrcItemId`=92766 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32376 AND `SrcItemId`=93019 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32382 AND `SrcItemId`=92950 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32383 AND `SrcItemId`=92950 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32397 AND `SrcItemId`=92950 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32421 AND `SrcItemId`=93159 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32446 AND `SrcItemId`=93180 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32455 AND `SrcItemId`=93362 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32493 AND `SrcItemId`=93806 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32525 AND `SrcItemId`=93751 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32528 AND `SrcItemId`=93803 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32555 AND `SrcItemId`=93806 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32569 AND `SrcItemId`=92060 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32588 AND `SrcItemId`=93761 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32589 AND `SrcItemId`=94123 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32594 AND `SrcItemId`=95432 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32599 AND `SrcItemId`=94155 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32600 AND `SrcItemId`=94197 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32601 AND `SrcItemId`=94198 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32602 AND `SrcItemId`=94199 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32621 AND `SrcItemId`=94721 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32628 AND `SrcItemId`=94905 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32637 AND `SrcItemId`=95360 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32686 AND `SrcItemId`=95383 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32687 AND `SrcItemId`=95384 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32688 AND `SrcItemId`=95385 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32689 AND `SrcItemId`=95386 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32690 AND `SrcItemId`=95387 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32691 AND `SrcItemId`=95388 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32692 AND `SrcItemId`=95389 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32693 AND `SrcItemId`=95390 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=32826 AND `SrcItemId`=94905 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=33022 AND `SrcItemId`=102372 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=33231 AND `SrcItemId`=104113 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=33232 AND `SrcItemId`=104110 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=33337 AND `SrcItemId`=105930 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=33354 AND `SrcItemId`=105891 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=33375 AND `SrcItemId`=105931 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=33376 AND `SrcItemId`=105932 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=33377 AND `SrcItemId`=105933 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=33378 AND `SrcItemId`=105934 AND `SrcItemCount`=0;
UPDATE `quest_template` SET `SrcItemCount`=1 WHERE `entry`=33379 AND `SrcItemId`=105935 AND `SrcItemCount`=0;

-- ReqSourceCountN set while ReqSourceIdN=0 (count is useless): 11 quest slot(s)
UPDATE `quest_template` SET `ReqSourceCount1`=0 WHERE `entry`=29893 AND `ReqSourceId1`=0 AND `ReqSourceCount1`=1;
UPDATE `quest_template` SET `ReqSourceCount2`=0 WHERE `entry`=29969 AND `ReqSourceId2`=0 AND `ReqSourceCount2`=1;
UPDATE `quest_template` SET `ReqSourceCount2`=0 WHERE `entry`=29970 AND `ReqSourceId2`=0 AND `ReqSourceCount2`=1;
UPDATE `quest_template` SET `ReqSourceCount1`=0 WHERE `entry`=30051 AND `ReqSourceId1`=0 AND `ReqSourceCount1`=3;
UPDATE `quest_template` SET `ReqSourceCount1`=0 WHERE `entry`=30584 AND `ReqSourceId1`=0 AND `ReqSourceCount1`=1;
UPDATE `quest_template` SET `ReqSourceCount1`=0 WHERE `entry`=30585 AND `ReqSourceId1`=0 AND `ReqSourceCount1`=1;
UPDATE `quest_template` SET `ReqSourceCount1`=0 WHERE `entry`=30698 AND `ReqSourceId1`=0 AND `ReqSourceCount1`=1;
UPDATE `quest_template` SET `ReqSourceCount1`=0 WHERE `entry`=30700 AND `ReqSourceId1`=0 AND `ReqSourceCount1`=1;
UPDATE `quest_template` SET `ReqSourceCount1`=0 WHERE `entry`=30753 AND `ReqSourceId1`=0 AND `ReqSourceCount1`=1;
UPDATE `quest_template` SET `ReqSourceCount1`=0 WHERE `entry`=30754 AND `ReqSourceId1`=0 AND `ReqSourceCount1`=1;
UPDATE `quest_template` SET `ReqSourceCount1`=0 WHERE `entry`=30763 AND `ReqSourceId1`=0 AND `ReqSourceCount1`=1;

-- RewSpellCast points to a spell removed from the 5.4.8 client (core drops the reward): 304 quest(s)
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=1652 AND `RewSpellCast`=5503;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=1785 AND `RewSpellCast`=7329;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=1788 AND `RewSpellCast`=7329;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=4490 AND `RewSpellCast`=5785;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=6085 AND `RewSpellCast`=1579;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=6088 AND `RewSpellCast`=1579;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=6089 AND `RewSpellCast`=5300;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=6102 AND `RewSpellCast`=1579;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=6103 AND `RewSpellCast`=5300;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=7463 AND `RewSpellCast`=10143;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=7583 AND `RewSpellCast`=20700;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=7631 AND `RewSpellCast`=23160;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=9364 AND `RewSpellCast`=28285;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=9485 AND `RewSpellCast`=1579;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=9593 AND `RewSpellCast`=1579;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=9600 AND `RewSpellCast`=7329;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=9673 AND `RewSpellCast`=5300;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=9675 AND `RewSpellCast`=5300;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=9685 AND `RewSpellCast`=7329;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=9691 AND `RewSpellCast`=5503;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=12228 AND `RewSpellCast`=28285;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=14006 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=14221 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=24681 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=25078 AND `RewSpellCast`=1579;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=25083 AND `RewSpellCast`=5300;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=25457 AND `RewSpellCast`=75027;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=25531 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=26727 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=26800 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=27378 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=27379 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=27858 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=27866 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=27898 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=27930 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=27965 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28028 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28029 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28030 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28061 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28062 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28099 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28134 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28172 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28177 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28178 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28179 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28183 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28184 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28187 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28253 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28310 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28311 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28312 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28313 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28321 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28351 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28417 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28419 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28420 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28421 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28425 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28426 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28436 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28442 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28443 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28444 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28445 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28455 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28513 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28518 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=28599 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29015 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29076 AND `RewSpellCast`=96363;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29095 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29128 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29198 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29205 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29208 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29239 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29254 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29257 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29278 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29299 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29326 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29546 AND `RewSpellCast`=119486;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29552 AND `RewSpellCast`=130915;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29553 AND `RewSpellCast`=103632;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29555 AND `RewSpellCast`=114032;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29561 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29619 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29621 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29628 AND `RewSpellCast`=103137;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29714 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29728 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29729 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29759 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29776 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29804 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29827 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29877 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29879 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29883 AND `RewSpellCast`=113342;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29885 AND `RewSpellCast`=113342;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29886 AND `RewSpellCast`=113342;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29887 AND `RewSpellCast`=103634;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29891 AND `RewSpellCast`=113625;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29892 AND `RewSpellCast`=113625;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29893 AND `RewSpellCast`=113625;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29894 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29896 AND `RewSpellCast`=102531;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29902 AND `RewSpellCast`=119486;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29904 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29905 AND `RewSpellCast`=113892;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29906 AND `RewSpellCast`=113892;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29910 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29911 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29912 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29914 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29915 AND `RewSpellCast`=118395;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29916 AND `RewSpellCast`=105812;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29917 AND `RewSpellCast`=105812;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29918 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29932 AND `RewSpellCast`=107001;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29940 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29941 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29990 AND `RewSpellCast`=111805;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=29999 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30000 AND `RewSpellCast`=114251;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30020 AND `RewSpellCast`=115045;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30050 AND `RewSpellCast`=108475;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30052 AND `RewSpellCast`=108380;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30054 AND `RewSpellCast`=108476;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30063 AND `RewSpellCast`=109716;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30067 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30068 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30069 AND `RewSpellCast`=119486;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30090 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30101 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30117 AND `RewSpellCast`=111805;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30131 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30136 AND `RewSpellCast`=110227;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30142 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30144 AND `RewSpellCast`=110702;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30150 AND `RewSpellCast`=130114;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30152 AND `RewSpellCast`=110889;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30157 AND `RewSpellCast`=110227;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30163 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30164 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30181 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30182 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30183 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30187 AND `RewSpellCast`=110854;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30240 AND `RewSpellCast`=128400;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30241 AND `RewSpellCast`=111805;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30242 AND `RewSpellCast`=128402;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30257 AND `RewSpellCast`=111721;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30261 AND `RewSpellCast`=128070;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30273 AND `RewSpellCast`=124412;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30274 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30277 AND `RewSpellCast`=128392;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30280 AND `RewSpellCast`=128404;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30354 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30357 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30360 AND `RewSpellCast`=111805;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30376 AND `RewSpellCast`=111805;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30445 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30466 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30469 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30484 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30495 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30498 AND `RewSpellCast`=114251;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30516 AND `RewSpellCast`=114422;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30524 AND `RewSpellCast`=114481;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30529 AND `RewSpellCast`=114620;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30565 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30568 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30584 AND `RewSpellCast`=125991;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30585 AND `RewSpellCast`=125991;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30586 AND `RewSpellCast`=125991;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30588 AND `RewSpellCast`=125991;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30598 AND `RewSpellCast`=125991;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30601 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30613 AND `RewSpellCast`=125991;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30614 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30617 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30618 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30621 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30627 AND `RewSpellCast`=146457;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30628 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30631 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30635 AND `RewSpellCast`=115576;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30636 AND `RewSpellCast`=115576;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30637 AND `RewSpellCast`=115576;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30641 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30642 AND `RewSpellCast`=116530;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30645 AND `RewSpellCast`=116156;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30649 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30650 AND `RewSpellCast`=126963;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30654 AND `RewSpellCast`=115576;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30655 AND `RewSpellCast`=126963;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30658 AND `RewSpellCast`=125991;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30673 AND `RewSpellCast`=119055;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30678 AND `RewSpellCast`=125991;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30680 AND `RewSpellCast`=119055;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30681 AND `RewSpellCast`=119055;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30682 AND `RewSpellCast`=119055;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30690 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30698 AND `RewSpellCast`=125991;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30700 AND `RewSpellCast`=125991;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30701 AND `RewSpellCast`=125991;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30715 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30723 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30725 AND `RewSpellCast`=116739;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30726 AND `RewSpellCast`=116739;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30727 AND `RewSpellCast`=116739;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30728 AND `RewSpellCast`=116739;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30729 AND `RewSpellCast`=116739;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30730 AND `RewSpellCast`=116739;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30731 AND `RewSpellCast`=116739;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30732 AND `RewSpellCast`=116739;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30733 AND `RewSpellCast`=116739;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30734 AND `RewSpellCast`=116739;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30735 AND `RewSpellCast`=116739;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30736 AND `RewSpellCast`=116739;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30737 AND `RewSpellCast`=116739;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30738 AND `RewSpellCast`=116739;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30739 AND `RewSpellCast`=116739;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30740 AND `RewSpellCast`=116739;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30753 AND `RewSpellCast`=125991;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30754 AND `RewSpellCast`=125991;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30763 AND `RewSpellCast`=125991;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30765 AND `RewSpellCast`=116857;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30774 AND `RewSpellCast`=117706;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30777 AND `RewSpellCast`=127609;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30781 AND `RewSpellCast`=118130;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30782 AND `RewSpellCast`=127688;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30783 AND `RewSpellCast`=127688;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30794 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30802 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30855 AND `RewSpellCast`=127839;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30930 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30935 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30941 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30955 AND `RewSpellCast`=121274;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30992 AND `RewSpellCast`=124154;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=30999 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31011 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31019 AND `RewSpellCast`=123468;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31026 AND `RewSpellCast`=128218;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31038 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31049 AND `RewSpellCast`=131432;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31061 AND `RewSpellCast`=131432;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31062 AND `RewSpellCast`=131432;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31082 AND `RewSpellCast`=123076;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31087 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31091 AND `RewSpellCast`=128888;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31092 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31117 AND `RewSpellCast`=131432;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31120 AND `RewSpellCast`=131432;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31147 AND `RewSpellCast`=73421;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31157 AND `RewSpellCast`=73663;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31179 AND `RewSpellCast`=123858;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31203 AND `RewSpellCast`=131432;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31204 AND `RewSpellCast`=131432;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31359 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31398 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31679 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31680 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31717 AND `RewSpellCast`=130087;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31718 AND `RewSpellCast`=130087;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31719 AND `RewSpellCast`=130087;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31720 AND `RewSpellCast`=130087;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31721 AND `RewSpellCast`=130087;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31733 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31739 AND `RewSpellCast`=130241;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31765 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31897 AND `RewSpellCast`=131398;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31915 AND `RewSpellCast`=131400;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31920 AND `RewSpellCast`=131404;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31928 AND `RewSpellCast`=131410;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=31970 AND `RewSpellCast`=131420;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=32212 AND `RewSpellCast`=138844;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=32243 AND `RewSpellCast`=133438;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=32277 AND `RewSpellCast`=139855;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=32279 AND `RewSpellCast`=139948;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=32296 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=32316 AND `RewSpellCast`=134440;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=32328 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=32340 AND `RewSpellCast`=134304;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=32352 AND `RewSpellCast`=134599;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=32366 AND `RewSpellCast`=134716;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=32367 AND `RewSpellCast`=134716;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=32384 AND `RewSpellCast`=135036;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=32507 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=32549 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=32644 AND `RewSpellCast`=139583;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=32652 AND `RewSpellCast`=139855;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=32656 AND `RewSpellCast`=139948;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=32809 AND `RewSpellCast`=142290;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=32810 AND `RewSpellCast`=81040;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=33229 AND `RewSpellCast`=148450;
UPDATE `quest_template` SET `RewSpellCast`=0 WHERE `entry`=33230 AND `RewSpellCast`=148450;

-- RewSpell (display reward) removed from client: 10 quest(s)
UPDATE `quest_template` SET `RewSpell`=0 WHERE `entry`=1652 AND `RewSpell`=5502;
UPDATE `quest_template` SET `RewSpell`=0 WHERE `entry`=6089 AND `RewSpell`=23357;
UPDATE `quest_template` SET `RewSpell`=0 WHERE `entry`=6103 AND `RewSpell`=23357;
UPDATE `quest_template` SET `RewSpell`=0 WHERE `entry`=7463 AND `RewSpell`=10140;
UPDATE `quest_template` SET `RewSpell`=0 WHERE `entry`=9451 AND `RewSpell`=8075;
UPDATE `quest_template` SET `RewSpell`=0 WHERE `entry`=9673 AND `RewSpell`=23357;
UPDATE `quest_template` SET `RewSpell`=0 WHERE `entry`=9675 AND `RewSpell`=23357;
UPDATE `quest_template` SET `RewSpell`=0 WHERE `entry`=9691 AND `RewSpell`=5502;
UPDATE `quest_template` SET `RewSpell`=0 WHERE `entry`=25083 AND `RewSpell`=23357;
UPDATE `quest_template` SET `RewSpell`=0 WHERE `entry`=25902 AND `RewSpell`=8071;

-- Quests completed by a spell (SPELL_EFFECT_QUEST_COMPLETE) missing QUEST_SPECIAL_FLAG_EXPLORATION_OR_EVENT (2): 128 quest(s)
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=28106 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=29604 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=29695 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=29697 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=29702 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=29704 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=29707 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=29708 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=29709 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=29805 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30207 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30208 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30209 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30210 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30211 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30212 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30215 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30216 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30217 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30218 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30219 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30220 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30221 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30222 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30223 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30224 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30454 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30455 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30470 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30486 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30536 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30566 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30629 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30647 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=30854 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31050 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31051 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31052 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31115 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31122 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31123 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31124 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31195 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31205 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31212 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31213 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31214 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31284 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31292 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31298 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31299 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31300 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31301 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31304 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31307 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31310 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31343 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31397 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31432 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31461 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31462 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31463 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31464 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31466 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31484 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31668 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31807 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31960 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31962 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31963 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31964 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31965 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=31969 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32098 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32099 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32112 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32258 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32259 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32260 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32261 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32306 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32339 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32357 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32477 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32518 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32519 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32609 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32610 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32611 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32626 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32629 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32640 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32641 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32727 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32744 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32745 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32746 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32747 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32748 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32749 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32750 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32751 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32752 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32753 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32754 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32755 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32756 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32832 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32860 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32864 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32865 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32866 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32919 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32922 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32923 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32924 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32956 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32957 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32961 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32962 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=32972 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=33109 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=33117 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=33118 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=33225 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=33226 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=33348 AND (`SpecialFlags`&2)=0;
UPDATE `quest_template` SET `SpecialFlags`=`SpecialFlags`|2 WHERE `entry`=33385 AND (`SpecialFlags`&2)=0;

        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
        -- -- PLACE UPDATE SQL ABOVE -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -

        -- If we get here ok, commit the changes
        IF bRollback = TRUE THEN
            ROLLBACK;
            SHOW ERRORS;
            SELECT '* UPDATE FAILED *' AS `===== Status =====`,@cCurResult AS `===== DB is on Version: =====`;
        ELSE
            COMMIT;
            -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
            -- UPDATE THE DB VERSION
            -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
            INSERT INTO `db_version` VALUES (@cNewVersion, @cNewStructure, @cNewContent, @cNewDescription, @cNewComment);
            SET @cNewResult := (SELECT `description` FROM `db_version` WHERE `version`=@cNewVersion AND `structure`=@cNewStructure AND `content`=@cNewContent);

            SELECT '* UPDATE COMPLETE *' AS `===== Status =====`,@cNewResult AS `===== DB is now on Version =====`;
        END IF;
    ELSE    -- Current version is not the expected version
        IF (@cCurResult = @cNewResult) THEN    -- Does the current version match the new version
            SELECT '* UPDATE SKIPPED *' AS `===== Status =====`,@cCurResult AS `===== DB is already on Version =====`;
        ELSE    -- Current version is not one related to this update
            IF(@cCurResult IS NULL) THEN    -- Something has gone wrong
                SELECT '* UPDATE FAILED *' AS `===== Status =====`,'Unable to locate DB Version Information' AS `============= Error Message =============`;
            ELSE
                IF(@cOldResult IS NULL) THEN    -- Something has gone wrong
                    SET @cCurVersion := (SELECT `version` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurStructure := (SELECT `STRUCTURE` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurContent := (SELECT `Content` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurOutput = CONCAT(@cCurVersion, '_', @cCurStructure, '_', @cCurContent, ' - ',@cCurResult);
                    SET @cOldResult = CONCAT('Rel',@cOldVersion, '_', @cOldStructure, '_', @cOldContent, ' - ','IS NOT APPLIED');
                    SELECT '* UPDATE SKIPPED *' AS `===== Status =====`,@cOldResult AS `=== Expected ===`,@cCurOutput AS `===== Found Version =====`;
                ELSE
                    SET @cCurVersion := (SELECT `version` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurStructure := (SELECT `STRUCTURE` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurContent := (SELECT `Content` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurOutput = CONCAT(@cCurVersion, '_', @cCurStructure, '_', @cCurContent, ' - ',@cCurResult);
                    SELECT '* UPDATE SKIPPED *' AS `===== Status =====`,@cOldResult AS `=== Expected ===`,@cCurOutput AS `===== Found Version =====`;
                END IF;
            END IF;
        END IF;
    END IF;
END $$

DELIMITER ;

-- Execute the procedure
CALL update_mangos();

-- Drop the procedure
DROP PROCEDURE IF EXISTS `update_mangos`;


